### ISSUE TITLE
when add the package it asks for Xamarin.Google.Android.Material reference

### ISSUE THREAD

**Issue by mohamadayash** [galadril/Xam.Shell.Badge#1]
Hello galadril , Thank you for the great work 

I've followed the documentation added the init for android and ios 

when add the package using nugets it asks for Xamarin.Google.Android.Material reference , I added the mentioned reference but no luck the badge didn't appear for android ,  it works normally for iOS 

![image](https://user-images.githubusercontent.com/11196273/90014654-2026f400-dcb0-11ea-87b4-3c4eaa76567f.png)

**Comment by galadril** [comment]
ill check in the library if it's really needed.. until then, please load and build the sample project.. to see if that works for you

**Comment by mohamadayash** [comment]
Yes @galadril I've run the android sample app , missing app icon in drawable , added the icon , the badge is showing 
I'll add the 3 source project to my app and give it a try

**Comment by galadril** [comment]
hmm thats then probably because of my last change to add some icons to the sample project & nuget, ill check that out

**Comment by galadril** [comment]
new nuget version is coming with v1.0.3. that added a fixed dependency with the Xamarin.Google.Android.Material library.
Im now fixing the sample project, so that should be there is couple of minutes

**Comment by galadril** [comment]
done
please check again
