### ISSUE TITLE
Inconsistent Look Between iOS and Android

### ISSUE THREAD

**Issue by darrabam** [galadril/Xam.Shell.Badge#11]
Hi there, 

Position and size of the badge seems to be different between the two platforms. On iOS it's okay, but on Android it is a bit off. Would be nice to make Android resembles the iOS view as much as possible.

![image](https://user-images.githubusercontent.com/33980667/98350872-fa9a5400-202c-11eb-9729-950f616a9823.png)

----
Also, on Android, the OS text size does affect the tiny badge position, i.e. setting the OS text size to largest makes the badge more at the bottom:
![image](https://user-images.githubusercontent.com/33980667/98351481-cb381700-202d-11eb-8f0b-e95729326ef1.png)

**Comment by SnowPowerCore** [comment]
Hello, @darrabam, consider checking the latest update 1.0.9 for nuget package 😃

**Comment by darrabam** [comment]
@SnowPowerCore 
1- Yes now the tiny badge looks much more consistent, thanks 👍 
2- The normal badges still look horrible on android when the OS text size is set to max.  
![image](https://user-images.githubusercontent.com/33980667/100746661-10175980-33f2-11eb-999f-34e0d0d9c267.png)


3- Also, the badge is not clearing when set to "" by the ViewModel ! any other value works as expected, but not empty string. I also tried string.empty which didn't work either. 
Thanks,

**Comment by SnowPowerCore** [comment]
Hello, @darrabam, yes, i investigated problem, i'm sorry, missed it when i was testing (i'm testing on both platforms, though). Fix will be applied soon, thank you. I won't be able to fix huge display of badge, when font size of the system is too large, in a near future, but i'm keeping this in mind...

**Comment by AdilSaiyad** [comment]
In iOS badge not showing please help me

**Comment by galadril** [comment]
1.0.10 is now available on nuget

**Comment by darrabam** [comment]
@SnowPowerCore on real devices like Samsung Galaxy S21 or S9 Plus (default font settings), the tiny badge is too large for some season 
![image](https://user-images.githubusercontent.com/33980667/111799038-b329ab80-88db-11eb-87d8-eeb8deb7aa8e.png)

Though it works fine on the Google pixel physical or emulator devices, OnePlus, Motorola .... etc.
Any quick hack that I can apply?

Thanks,

**Comment by SnowPowerCore** [comment]
@darrabam, i know this is occasional and you may not be involved into using this library as of now, but i've introduced new logic for Android Badges within my recent PR #24. Sorry that it took almost a year to return.

**Comment by SnowPowerCore** [comment]
If this is still relevant for Android, please, create new issue, but i think #24 should pretty much resolve it due to the offloading of the entire logic to the Material Components Library Badge feature ([read here](https://github.com/material-components/material-components-android/blob/master/docs/components/BadgeDrawable.md)).
