### ISSUE TITLE
Question: Xaml Code-Behind

### ISSUE THREAD

**Issue by dgerding** [galadril/Xam.Shell.Badge#13]
Hi,
Thanks for this great addition to Xamarin. I'm looking forward to it being merged into main Shell implementation.

In the meantime, I have an embarrassing question. I can't remember the right xaml code-behind approach.

Assuming I've got the following xaml in my AppShell.xaml
```
 <Tab
             x:Name="SomeTab"
            Title="Test1"
            badge:Badge.BackgroundColor="Red"
            badge:Badge.Text="2">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
```
What's the right way to reference the badge from the AppShell.xaml.cs code-behind so I can call Badge.SetText from there? I can reference the Tab, just can't remember the right way to reference the badge property of the Tab element.

Thanks for any guidance!!

Dave G

**Comment by SnowPowerCore** [comment]
Hello @dgerding, you should use Badge.SetText(SomeTab, "2"). First argument is Tab instance, second - actual text value 😉

**Comment by galadril** [comment]
@dgerding  please close this issue if the info provided by @SnowPowerCore  was enough.

**Comment by dgerding** [comment]
@SnowPowerCore Thanks for the help. So, should I not use xaml declaration at all? I get the badge to appear and work when I use only code-behind approach. But the button is a little large for the available space and I imagined there might be sizing or other properties eventually available from Xaml side. Is the pattern going to be "code behind only" and should I get rid of the Xaml declaration? Thanks.
