### ISSUE TITLE
Xamarin iOS Shell Tabbbar sometime showing but sometime not showing badge count

### ISSUE THREAD

**Issue by AdilSaiyad** [galadril/Xam.Shell.Badge#15]
Hello 
I have implement badge in Shell tabbar so it's working fine in Android but in iOS not working.
Example code
```
<Shell
xmlns:badge="clr-namespace:Xam.Shell.Badge;assembly=Xam.Shell.Badge">
<TabBar Route="Tab">
      <Tab Title="{language:Translate ProfileText}"
             Icon="profile_icon.png"
             badge:Badge.BackgroundColor="Red"
             badge:Badge.Text="{Binding ProfileBadgeCount}"
             Route="Tab4">
            <ShellContent Route="ProfilePage"
                          ContentTemplate="{DataTemplate dashboardViews:ProfilePage}" />
        </Tab>
</TabBar>
</Shell>
```

**Comment by AdilSaiyad** [comment]
Please anyone help me.

**Comment by galadril** [comment]
Did you run the Init in you AppDelegate?

`            BottomBar.Init();`

**Comment by AdilSaiyad** [comment]
> Did you run the Init in you AppDelegate?
> 
> ` BottomBar.Init();`

Yes i have added

**Comment by galadril** [comment]
This is checked against v1.0.10?

**Comment by AdilSaiyad** [comment]
Yes

> This is checked against v1.0.10?

Yes.

**Comment by AdilSaiyad** [comment]
Hello @galadril 
have you resolved this issue?

**Comment by angelru** [comment]
any update?

**Comment by AdilSaiyad** [comment]
> any update?

Not yet...please resolved issue

**Comment by galadril** [comment]
Really busy at the moment, please create a PR if you find the fix

**Comment by jtorvald** [comment]
@AdilSaiyad I had a similar problem. I binded a int property with the value zero. If you look into the source of this library you'll see in iOS/Renderers/BadgeShellItemRenderer:76 (ApplyBadge) that it will show a ● with the color UIColor.Clear.
That results in some grey dot in my case.

Basically I think that this ● can be set to NULL there but I don't know what @galadril  had in mind here. 

So to solve my issue is that I wrote a ValueConverter that converts an int that is zero to NULL and that's it.

```

    public class NumberToBadgeConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (targetType == typeof(string) && value is int && (int)value == 0)
                return null;
                
            return value;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value;
        }
    }

```

**Comment by AdilSaiyad** [comment]
Thanks for your reply

I'll check it out.

Thanks & Best Regards
Adil Saiyad

**Comment by angelru** [comment]
This package will no longer receive updates?

**Comment by jtorvald** [comment]
@angelru like with all open source I guess it depends on the time of the maintainer(s).
@galadril said he is busy, so if there is issues other people can also look into it and submit a pull request.

**Comment by SnowPowerCore** [comment]
@angelru, please, try the latest v.1.0.12 package. If you still experience this issue, feel free to create new issue.
