### ISSUE TITLE
Xamarin Android After add badge count tab selection color not showing for tab icon.

### ISSUE THREAD

**Issue by AdilSaiyad** [galadril/Xam.Shell.Badge#16]
Please check below image when i select tab for implemented badge count then selection color for tab-icon is not showing.

![Screenshot 2020-12-21 at 1 21 27 PM](https://user-images.githubusercontent.com/45910754/102753031-845d7100-4390-11eb-90ce-b367b85dfdd7.png)

**Comment by Martin-4Spaces** [comment]
I can confirm this issue.

**Comment by galadril** [comment]
This is checked against v1.0.10?

**Comment by Martin-4Spaces** [comment]
Yes.

**Comment by AdilSaiyad** [comment]
Yes.

**Comment by angelo-p82** [comment]
On 1.0.11 same issue

**Comment by AdilSaiyad** [comment]
> On 1.0.11 same issue

but 1.0.11 is not available right now

**Comment by angelo-p82** [comment]
> > On 1.0.11 same issue
> 
> but 1.0.11 is not available right now

In Visual Studio latest version available is 1.0.11

**Comment by AdilSaiyad** [comment]
> > > On 1.0.11 same issue
> > 
> > 
> > but 1.0.11 is not available right now
> 
> In Visual Studio latest version available is 1.0.11

Same issue in 1.0.11

**Comment by angelru** [comment]
any update?

**Comment by AdilSaiyad** [comment]
> any update?

Not Yet...Please resolved issue

**Comment by galadril** [comment]
Really busy at the moment, please create a PR if you find the fix

**Comment by angelru** [comment]
> > any update?
> 
> Not Yet...Please resolved issue

can you create a PR?

**Comment by AdilSaiyad** [comment]
> > > any update?
> > 
> > 
> > Not Yet...Please resolved issue
> 
> can you create a PR?

I'm currently busy with other task.

**Comment by angelru** [comment]
> > > > any update?
> > > 
> > > 
> > > Not Yet...Please resolved issue
> > 
> > 
> > can you create a PR?
> 
> I'm currently busy with other task.

ups...

**Comment by rayita** [comment]
Any news on this?

**Comment by gigimatto88** [comment]
In 1.0.11 the selected tab has icon color different from the tab title color. While in 1.0.8 this was working...

**Comment by angelru** [comment]
since this no longer holds, the solution is to use shell + tabview or https://www.sharpnado.com/pure-xamarin-forms-tabs/

**Comment by pp111** [comment]
It seems that the image color was lost when it was removed and added to the view again
I fixed this issue by just removing in BadgeHelper.cs the lines
`bottomNavigationView.RemoveView(imageView);`
and
`badgeContainerFrameLayout.AddView(imageView)`

for the functions ApplyBadge and ApplyTinyBadge.

It seems to work correctly now, however I don't know if these lines had another purpose.

**Comment by Law85** [comment]
@pp111 I think this was done so that the image can be placed inside of the BadgeContainer to ensure its was positioned within its parent correctly. When I removed these lines it resulted in fixing the issue but the badges weren't  quite right.  I have tweaked around with the layout options a little and I think I have managed to fix it.

@galadril. I have created a PR for this issue, please let me know you see any issues

**Comment by SnowPowerCore** [comment]
@rayita @angelru, this may not be recent for you anymore, but i've introduced new logic for rendering badges on Android with the following PR: #24. If you're still interested, you may check it out.

**Comment by SnowPowerCore** [comment]
@rayita, @angelru, try the new v.1.0.12 of the Nuget package. If you still experience problem, feel free to create new issue.
