### ISSUE TITLE
Xamarin Forms Shell tab automatically change 

### ISSUE THREAD

**Issue by AdilSaiyad** [galadril/Xam.Shell.Badge#19]
When I have set badge in shell tab bar and in this I have applied multiple language, so if I change language from English to Afrikaans then badge automatically switch to another tab.

It's not working for multiple language.

Please solve all issue.

Thanks in advance!

**Comment by SnowPowerCore** [comment]
@AdilSaiyad, this may not be recent for you anymore, but if occasionally it is, can you check the updated logic with the #24 PR?

**Comment by SnowPowerCore** [comment]
@AdilSaiyad, a new v.1.0.12 has been introduced. If you still experience this problem, feel free to create new issue.
