### ISSUE TITLE
When add style to Tabbar badge doesn't appears on android

### ISSUE THREAD

**Issue by mohamadayash** [galadril/Xam.Shell.Badge#2]
Hello @galadril 

When I add a style to tabbar the badge doesn't appear 

`
<?xml version="1.0" encoding="UTF-8"?>
<Shell xmlns="http://xamarin.com/schemas/2014/forms" 
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:d="http://xamarin.com/schemas/2014/forms/design"
       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
       mc:Ignorable="d"
       xmlns:local="clr-namespace:App3.Views"
       Title="App3"
       x:Class="App3.AppShell">

    
    <Shell.Resources>
        <ResourceDictionary>
            <Color x:Key="NavigationPrimary">#2196F3</Color>
            <Style x:Key="BaseStyle" TargetType="Element">
                <Setter Property="Shell.BackgroundColor" Value="{StaticResource NavigationPrimary}" />
                <Setter Property="Shell.ForegroundColor" Value="White" />
                <Setter Property="Shell.TitleColor" Value="White" />
                <Setter Property="Shell.DisabledColor" Value="#B4FFFFFF" />
                <Setter Property="Shell.UnselectedColor" Value="#95FFFFFF" />
                <Setter Property="Shell.TabBarBackgroundColor" Value="{StaticResource NavigationPrimary}" />
                <Setter Property="Shell.TabBarForegroundColor" Value="White"/>
                <Setter Property="Shell.TabBarUnselectedColor" Value="#95FFFFFF"/>
                <Setter Property="Shell.TabBarTitleColor" Value="White"/>
            </Style>
            <Style TargetType="TabBar" BasedOn="{StaticResource BaseStyle}" />
        </ResourceDictionary>
    </Shell.Resources>

    
    <TabBar x:Name="tabBar">
        <Tab Title="Test1">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Title="Test2">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Title="Test3">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Title="Test4">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
    </TabBar>

    

</Shell>

`

**Comment by darrabam** [comment]
@mohamadayash I’m also facing this, did you manage to find a workaround?

@galadril any workaround? or pointers on where should I look for to fix this?

**Comment by angelru** [comment]
@darrabam @mohamadayash @galadril 

 the tab bar appears all blank in the CustomShellRenderer I added this to style it in SetAppearance:

```
             // Change colors on different states
             int [] [] states = new int [] []
             {
                 new int [] {- Android.Resource.Attribute.StateChecked}, // unchecked
                 new int [] {Android.Resource.Attribute.StateChecked}, // checked
                 new int [] {} // default
             };

             int [] colors = new int []
             {
                 Android.Graphics.Color.ParseColor ("Hex"),
                 Android.Graphics.Color.White,
                 Android.Graphics.Color.ParseColor ("Hex"),
             };

             ColorStateList navigationViewColorStateList = new ColorStateList (states, colors);
            bottomView.ItemIconTintList = navigationViewColorStateList;
            bottomView.ItemTextColor = navigationViewColorStateList;
```

**Comment by galadril** [comment]
Duplicate #7

**Comment by angelru** [comment]
any solution? the layout is not applied in android from the xaml in shell

**Comment by galadril** [comment]
Please update to v1.0.8.
Look at the sample project, its also now styling via:

`<Shell.Resources>
    <ResourceDictionary>
        <Color x:Key="NavigationPrimary">#2196F3</Color>
        <Style x:Key="BaseStyle" TargetType="Element">
            <Setter Property="Shell.BackgroundColor" Value="{StaticResource NavigationPrimary}" />
            <Setter Property="Shell.ForegroundColor" Value="White" />
            <Setter Property="Shell.TitleColor" Value="White" />
            <Setter Property="Shell.DisabledColor" Value="#B4FFFFFF" />
            <Setter Property="Shell.UnselectedColor" Value="#95FFFFFF" />
            <Setter Property="Shell.TabBarBackgroundColor" Value="{StaticResource NavigationPrimary}" />
            <Setter Property="Shell.TabBarForegroundColor" Value="White"/>
            <Setter Property="Shell.TabBarUnselectedColor" Value="#95FFFFFF"/>
            <Setter Property="Shell.TabBarTitleColor" Value="White"/>
        </Style>
        <Style TargetType="TabBar" BasedOn="{StaticResource BaseStyle}" />
    </ResourceDictionary>
</Shell.Resources>`

Please close the issue if you agree

**Comment by angelru** [comment]
many thanks!

I have a question, how to link the properties? to handle it from a viewmodel

**Comment by SnowPowerCore** [comment]
> many thanks!
> 
> I have a question, how to link the properties? to handle it from a viewmodel

Hello, @angelru, just like w/ regular properties in a regular manner. You provide BindingContext to the entire page (yes, in this case it will be `Shell`) and then you can do `badge:Badge.Text="{Binding FavoriteItemsCount}"`.

**Comment by darrabam** [comment]
@SnowPowerCore Thanks for your help. Seems like the api have change considerably. I'm trying to set the badge from the code-behind after receiving a notification from the message center i.e. in my AppShell.xaml.cs:
`            MessagingCenter.Subscribe<ItemDetailViewModel, BasketItem>(this, "ItemAdded", async (sender, arg) =>
            {
                Badge.SetText(this.basketPage, "0");
                Badge.SetBackgroundColor(this.basketPage, Color.Red);
            });
`
The code does execute, but no effect. this.basketPage is the name of the tab
`        <Tab x:Name="basketPage" badge:Badge.BackgroundColor="#689F39" Title="{x:Static resources:AppResources.Basket}" Icon="basket.png">
            <ShellContent x:Name="basketPageTemplate" ContentTemplate="{DataTemplate local:BasketPage_ar}" />
        </Tab>`

It used to be new BottomBarHelper().SetTinyBadge(1, Color.Red)  , but now BottomBarHelper is gone.

**Comment by SnowPowerCore** [comment]
> @SnowPowerCore Thanks for your help. Seems like the api have change considerably. I'm trying to set the badge from the code-behind after receiving a notification from the message center i.e. in my AppShell.xaml.cs:
> ` MessagingCenter.Subscribe<ItemDetailViewModel, BasketItem>(this, "ItemAdded", async (sender, arg) => { Badge.SetText(this.basketPage, "0"); Badge.SetBackgroundColor(this.basketPage, Color.Red); });`
> The code does execute, but no effect. this.basketPage is the name of the tab
> ` <Tab x:Name="basketPage" Title="{x:Static resources:AppResources.Basket}" Icon="basket.png"> <ShellContent x:Name="basketPageTemplate" ContentTemplate="{DataTemplate local:BasketPage_ar}" /> </Tab>`
> 
> It used to be new BottomBarHelper().SetTinyBadge(1, Color.Red) , but now BottomBarHelper is gone.

@darrabam, thank you. Yes, mechanism has changed: no longer should you use code-behind approach (you can, though, please read [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/attached-properties#consume-an-attached-property)), but you should control the value directly in XAML. You can read more in the PR #8 .

**Comment by darrabam** [comment]
@SnowPowerCore  Thanks for your prompt reply. I did create a ShellViewModel and setup things as normal mvvm, however that didn't work. 

Then I set everything statically in the xaml (like the documentation, just for testing) and that also didn't work either! 
Both, Android and iOS. XF:4.8.0.1560. Not sure what could be wrong.

Finally, I did try with a new clean project "Tab Template" , updated all the packages to the latest stable releases, set the badges statically like in the documentation, but still doesn't work! probably there is step missing is the documentation 

Thanks,

**Comment by SnowPowerCore** [comment]
> @SnowPowerCore Thanks for your prompt reply. I did create a ShellViewModel and setup things as normal mvvm, however that didn't work.
> 
> Then I set everything statically in the xaml (like the documentation, just for testing) and that also didn't work either!
> Both, Android and iOS. XF:4.8.0.1560. Not sure what could be wrong.
> 
> Finally, I did try with a new clean project "Tab Template" , updated all the packages to the latest stable releases, set the badges statically like in the documentation, but still doesn't work! probably there is step missing is the documentation
> 
> Thanks,

@darrabam can you publish your repo? Let's look into the code.

**Comment by darrabam** [comment]
@SnowPowerCore thanks! there you go: https://github.com/darrabam/BadgeTest
Note also that in Android, using Xam.Shell.Badge.Android is unrecognized, although the nuget package was installed.

**Comment by SnowPowerCore** [comment]
> @SnowPowerCore thanks! there you go: https://github.com/darrabam/BadgeTest
> Note also that in Android, using Xam.Shell.Badge.Android is unrecognized, although the nuget package was installed.

Can you try to place <Tab> in between of <TabBar> and <ShellContent> and assign all badge:... props to <Tab> element?

**Comment by darrabam** [comment]
> Can you try to place `<Tab>` in between of `<TabBar>` and `<ShellContent>` and assign all badge:... props to `<Tab>` element?

Yes! this did the trick for the blank project. But for my actual project, still not showing the badges. I'll try to replicate the issue and post another project. 
Many thanks,

**Comment by darrabam** [comment]
@SnowPowerCore This is to confirm that it is working fine. The issue I mentioned about about my project was due to the fact that I had a CustomShellRenderer for my Android project.
Thanks again,
