### ISSUE TITLE
Badge doesn't appear when using CustomShellRenderer (both, iOS and Android)

### ISSUE THREAD

**Issue by sahil-khanna** [galadril/Xam.Shell.Badge#20]
I'm using a `CustomShellRenderer` for both iOS and Android. The issue is as below

- When a `CustomShellRenderer` is used, the badges do not appear.
- Commenting the below line in the `CustomShellRenderer` displays the badges
`[assembly: ExportRenderer(typeof(FB.Views.IssuerStartPage), typeof(IssuerShellRenderer))]`

Can anyone guide me to display the badges along with a `CustomShellRenderer`

**Comment by MNADEEMCH** [comment]
@sahil-khanna  I also facing the same issue on both iOS and Android with custom shell renderer

there is my renderer and in BottomTabBar m doing my stuff.
public class AppShellRenderer : ShellRenderer
    {
        public AppShellRenderer(Context context) : base(context)
        {
        }

        protected override IShellBottomNavViewAppearanceTracker CreateBottomNavViewAppearanceTracker(ShellItem shellItem)
        {
            return new BottomTabBar(Element);
        }
    }

**Comment by TanishqThakral** [comment]
@sahil-khanna @MNADEEMCH @galadril   Have you found any workaround for this issue ?

**Comment by SnowPowerCore** [comment]
You may implement the same logic as this library does by visiting sources and adding related code into the necessary platform renderers.

**Comment by SnowPowerCore** [comment]
Also, @sokrog, check out my #24 PR for easier and more straightforward implementation of Badges for Android.

**Comment by sokrog** [comment]
> You may implement the same logic as this library does by visiting sources and adding related code into the necessary platform renderers.

I have already resolve my problem by adding related code to my project, thanks all =)

**Comment by galadril** [comment]
Looks like i've issues with the latest nuget because of my build setup..

**Comment by TanishqThakral** [comment]
@galadril Is this issue fixed now?
