### ISSUE TITLE
Xam.Shell.Badge 1.0.15 depends on Xamarin.Forms (>= 4.0.0)

### ISSUE THREAD

**Issue by jtorvald** [galadril/Xam.Shell.Badge#27]
In my package console I get:
Xam.Shell.Badge 1.0.15 depends on Xamarin.Forms (>= 4.0.0) but Xamarin.Forms 4.0.0 was not found. An approximate best match of Xamarin.Forms 4.0.0.425677 was resolved.

Not sure if this is an issue, but isn't there dependency tag to say that it also supports 5?

**Comment by SnowPowerCore** [comment]
Hello, @jtorvald, version `5.0.0.2291` was used as a dependency for the sources of this library. You may try to upgrade your projects (both `.NET Standard` and platform ones) to this version to resolve this console warning.

**Comment by jtorvald** [comment]
Argh, I was supposed to be in bed already when I reporting this. I'm trying to fix an issue in Xamarin Forms so I referenced the development branch and therefor it can not find the package. Apologies for stealing your time.
