### ISSUE TITLE
error XA2002: Can not resolve reference: `AsyncAwaitBestPractices`

### ISSUE THREAD

**Issue by jtorvald** [galadril/Xam.Shell.Badge#28]
Are you aware of this? Is it intentional or a mistake?

error XA2002: Can not resolve reference: `AsyncAwaitBestPractices`, referenced by `Xam.Shell.Badge.Android`. Please add a NuGet package or assembly reference for `AsyncAwaitBestPractices`, or remove the reference to `Xam.Shell.Badge.Android`.

**Comment by SnowPowerCore** [comment]
Hello, i'm not sure this should be the problem since `AsyncAwaitBestPractices` is a .NET Standard library, thus should be compatible with android and iOS projects... Anyway, this issue was a good base for me too re-visit Nuget dependencies and clean them up. Changes are available with the PR #30.

**Comment by jtorvald** [comment]
It's not that it didn't get added from the dependencies after instating the package. Thanks for the quick follow up
