### ISSUE TITLE
CustomShellRenderer class should be public 

### ISSUE THREAD

**Issue by mohamadayash** [galadril/Xam.Shell.Badge#3]
CustomShellRenderer class should be public so we can inherit from it

**Comment by galadril** [comment]
Im open for a PR, just created this library quickly to show how to implement badges

**Comment by tkouba** [comment]
And name should be changed to BadgeShellRenderer

**Comment by SnowPowerCore** [comment]
Hello @mohamadayash, starting from 1.0.9 version, renderers are public :3

**Comment by SnowPowerCore** [comment]
Hello, @tkouba, your request is done 😃
