### ISSUE TITLE
Badge doesn't contain the text

### ISSUE THREAD

**Issue by Imodejam** [galadril/Xam.Shell.Badge#32]
Hi, I'm trying to insert the badge into a TabBar and binding the text with a property.
The effect is that the text is filled but the badge doesn't contain the text. It's size doesn't grow up the the text.

![Immagine 2022-02-28 185802](https://user-images.githubusercontent.com/94759037/156034536-014ec71d-0213-4659-8f03-4698c0fb1ceb.png)

this is the text of the form
  
        <Tab
            Title="{translator:Translate NOTIFICATIONS}"
            badge:Badge.BackgroundColor="Red"
            badge:Badge.Text="{Binding NotificationCount}">
            <ShellContent ContentTemplate="{DataTemplate local:NotificationsPage}" />
            <Tab.Icon>
                <FontImageSource FontFamily="MR" Glyph="notifications_none" Size="Small"/>
            </Tab.Icon>
        </Tab>

and this is the propery:

 public string NotificationCount
        {
            get => notificationCount;
            set => SetProperty(ref notificationCount, value);
        }

@galadril

**Comment by slprog1** [comment]
Hello,

I'm facing a number of related issues, I guess. 
The badge only works when i set its value to any number, when the text is set to "0", it is shown with weird white circle in it. Also setting background color does not work, neither setting text color.

I'm running on the latest Xamarin.Forms version 5.0.02337
Maybe that is the reason of such huge amounts of issues I'm currently facing. 
Running the app on the Simulator results in application crash

<img width="1029" alt="Screenshot 2022-03-04 at 23 24 46" src="https://user-images.githubusercontent.com/5887079/156844372-6c9f182f-4c5f-4421-b949-f0cbfe3cf30b.png">

**Comment by SnowPowerCore** [comment]
@Imodejam @slprog1, can you re-test with the latest 1.0.19 Nuget package? This issue should be resolved for you now.

**Comment by SnowPowerCore** [comment]
@Imodejam, hello, do you have any updates on the status of this issue? As far as i can test, this should be working good right now, especially after changes on the Android renderer...

**Comment by SnowPowerCore** [comment]
@Imodejam, hello, i'll be closing this issue due to the test i performed. It should be working now.
