### ISSUE TITLE
Badge not Showing up

### ISSUE THREAD

**Issue by krunalBagadia** [galadril/Xam.Shell.Badge#35]
Thanks for Plugin first of all. it works well in IOS but for and Android if TabBarBackgroundColor="White" Badge is not showing up.

Please share your thoughts asap so i can use it well into my proj.

**Comment by SnowPowerCore** [comment]
Hello, @krunalBagadia, you can change badge color to not to match the TabBar color by changing the Badge.BackgroundColor & Badge.TextColor. It should work with no problem for Android too.

**Comment by SnowPowerCore** [comment]
Hello, @krunalBagadia, i've identified this issue. Fix is coming up.

**Comment by SnowPowerCore** [comment]
Hello, @krunalBagadia, i've tested this thoroughly, and i can confirm this issue is resolved. If you experience any other problem in future, feel free to create new issues.
