### ISSUE TITLE
ObjectDisposedException: Cannot access a disposed object on ShellFlyoutRenderer

### ISSUE THREAD

**Issue by mcapplication20** [galadril/Xam.Shell.Badge#38]
Hello. In 1.0.19 version I got "Cannot access a disposed object on BottomNavigationView". now it seems issue is fixed but I got another "Cannot access a disposed object", and it's "xamarin.forms.platform.android.shellflyoutrenderer"

I'm using: 

Xamarin.forms 5.0.0.2337
Xam.Shell.Badge 1.0.20

No issue on iOS

**Comment by SnowPowerCore** [comment]
@mcapplication20, thank you, i'll investigate your issue. There shouldn't be any change in the "xamarin.forms.platform.android.shellflyoutrenderer" from this library.

**Comment by mcapplication20** [comment]
I’ll make some different prove and I’ll update you

**Comment by mcapplication20** [comment]
Update: it seems I did a mistake in my code, plugin is working perfectly even on android devices. I have some issue handling notifications but it's not linked to plugin. thanks for your incredible work

**Comment by SnowPowerCore** [comment]
@mcapplication20, hello, oh, good, thank you for this information.

**Comment by mcapplication20** [comment]
UPDATE: anyway it seems I got issue only when I install this plugin. I'm using Azure notification and Plugin.AzurePushNotification to handle notifications. When app is in background and user clicks on notification, CrossAzurePushNotification.Current.OnNotificationReceived fires. In this method I "push" user to the right page and I got issue. no problem on iOS and no problem on android without plugin

**Comment by SnowPowerCore** [comment]
> UPDATE: anyway it seems I got issue only when I install this plugin. I'm using Azure notification and Plugin.AzurePushNotification to handle notifications. When app is in background and user clicks on notification, CrossAzurePushNotification.Current.OnNotificationReceived fires. In this method I "push" user to the right page and I got issue. no problem on iOS and no problem on android without plugin

Try to invoke the navigation code using Device.InvokeOnMainThreadAsync.

**Comment by mcapplication20** [comment]
> 

Same issue with Device.BeginInvokeOnMainThread and Device.InvokeOnMainThreadAsync

**Comment by mcapplication20** [comment]
after a lot of work, I confirm that plugin works like a charm; it's my code issue. so thank you very much for your incredible work and support

**Comment by SnowPowerCore** [comment]
@mcapplication20, hello, thank you for information. Good that you're able to resolve situation.
