### ISSUE TITLE
Crash Xiomi in release mode.

### ISSUE THREAD

**Issue by nellogaudino** [galadril/Xam.Shell.Badge#39]
Hi, in my Xamarin android app I use Xamarin.Shell.Badge in Tab control; it work fine when I test app on my Xiomi physical device (debug mode); when I test my app in release mode or thought Google Play Store beta test, the app crash. The error is:

LOG: MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
[MonoDroid] --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
[MonoDroid] android.runtime.JavaProxyThrowable: System.MissingMethodException: Default constructor not found for type Xam.Shell.Badge.Droid.Renderers.BadgeShellRenderer

Thank you.

**Comment by SnowPowerCore** [comment]
Hello, @nellogaudino, when you set your Linker behaviour to None, do you have the same problem appearing? Can you re-create the release and try with this setting?

**Comment by nellogaudino** [comment]
Hello, when I set linker behavior to "None" or to "Link SDK assemblies only" all work fine. My previous setting was "Link all assemblies"
Thank you!

**Comment by SnowPowerCore** [comment]
Yes, please, use "Link SDK assemblies only" or configure your Linker settings file deeply. It is really rare to use "Link all assemblies" option, cause it may lead to unpredictable errors and you don't save much APK size in comparison with "Link SDK assemblies only" (recommended option).
