### ISSUE TITLE
Attached properties approach

### ISSUE THREAD

**Issue by SnowPowerCore** [galadril/Xam.Shell.Badge#5]
Hello @galadril. Instead of using code-behind, can you please think about implementing attached properties, so that we could use functionality within XAML? Here's article from Xamarin Docs: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/attached-properties

**Comment by galadril** [comment]
you could make a PR ;)

**Comment by SnowPowerCore** [comment]
> you could make a PR ;)

true!
okay, i'll do it this evening (UTC+6)

**Comment by galadril** [comment]
Thanks!

**Comment by SnowPowerCore** [comment]
@galadril sorry for a little delay: just published PR #8 . Please, accept my invitation to be a collaborator, so you would be able to be assigned as a reviewer. Hope you enjoy changes, we can discuss them if you want;

**Comment by galadril** [comment]
Ive checked the code a little bit, so that the smaller notifications are more like a circle.

![image](https://user-images.githubusercontent.com/14561640/96969211-6bf8e380-1512-11eb-8bcc-7b4a91ee64bd.png)

**Comment by galadril** [comment]
I also changed the badge interface naming a little bit

```
badge:Badge.Text
badge:Badge.BackgroundColor
badge:Badge.TextColor
```

Thanks for your awesome work.. 
Nuget is uploaded v1.0.8
Readme is adjusted

thanks
