### ISSUE TITLE
Tabbar stays visible as a white empty bar on iOS even when Shell.TabBarIsVisible is set to false

### ISSUE THREAD

**Issue by calvinbaart** [galadril/Xam.Shell.Badge#9]
Looking at the code it seems to be causes by the iOS renderers forcing Translucent to false. If I recompile the package without those lines in CustomShellRenderer then the bar correctly hides away.

**Comment by galadril** [comment]
ill test it if you make a PR ;)

**Comment by SnowPowerCore** [comment]
Hello, @calvinbaart, consider checking the latest nuget package: it has translucency lines removed too!
